# Generated by Django 5.2.5 on 2025-08-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisis",
            name="protocolo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
