# Generated by Django 5.2.5 on 2025-08-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serology', '0004_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisis',
            name='es_urgente',
        ),
        migrations.RemoveField(
            model_name='analisis',
            name='impreso',
        ),
        migrations.AddField(
            model_name='pedido',
            name='es_urgente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='impreso',
            field=models.BooleanField(default=False),
        ),
    ]
