# Generated by Django 5.2.5 on 2026-01-10 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "serology",
            "0005_remove_analisis_es_urgente_remove_analisis_impreso_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipoanalisis",
            options={
                "verbose_name": "Test-Método",
                "verbose_name_plural": "Test-Métodos",
            },
        ),
        migrations.AlterField(
            model_name="analisis",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="fecha",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="PerfilPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipos_analisis",
                    models.ManyToManyField(
                        related_name="perfiles", to="serology.tipoanalisis"
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de pedido",
                "verbose_name_plural": "Perfiles de pedido",
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="perfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="serology.perfilpedido",
            ),
        ),
    ]
