# Generated by Django 5.2.5 on 2026-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serology", "0007_paciente_sexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="telefono",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
