# Generated by Django 5.2.5 on 2026-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serology", "0008_paciente_telefono"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticoBoton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("texto", models.CharField(max_length=255)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Boton de diagnostico",
                "verbose_name_plural": "Botones de diagnostico",
                "ordering": ("orden", "label"),
            },
        ),
    ]
